language: "vi"

pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "CountVectorsFeaturizer"
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "DIETClassifier"
  epochs: 100




policies:
- name: "MemoizationPolicy"
  max_history: 5
- name: "TEDPolicy"
  max_history: 5
  epochs: 100
  constrain_similarities: true
- name: "RulePolicy"
assistant_id: 20250513-085241-searing-avocet
